#!/bin/bash
. /root/config.sh
mkdir /home/_apt
chown _apt /home/_apt
apt update
apt install --yes sudo
apt install --yes vim
apt install --yes systemd
apt install --yes bash
apt install --yes openssl
apt install --yes curl
apt install --yes net-tools
useradd -m "$USER"
usermod -aG sudo "$USER"
usermod --password $(openssl passwd -1 "$PASSWORD") root
usermod --password $(openssl passwd -1 "$PASSWORD") "$USER"
usermod --shell /bin/bash "$USER"
