#!/bin/bash
mkdir /home/_apt
chown _apt /home/_apt
apt update
apt install --yes sudo
apt install --yes vim
apt install --yes systemd
apt install --yes bash
apt install --yes openssl
apt install --yes curl
apt install --yes net-tools
useradd -m user
usermod -aG sudo user
usermod --password $(echo testing123 | openssl passwd -1 -stdin) root
usermod --password $(echo testing123 | openssl passwd -1 -stdin) user
usermod --shell /bin/bash user